## Tensorflow fundamental exercise

In [1]:
import numpy as np
import tensorflow as tf

In [4]:
# Defining a vector
ten1 = tf.constant([1,2,3])
ten1.ndim

1

In [7]:
ten2 = tf.constant(5)
ten2.ndim   # this is a scaler tensor

0

In [8]:
ten3 = tf.constant([[2,5],[6,7]])
ten3.ndim

2

In [10]:
ten4 = tf.constant([[[2,5,6],
                    [4,6,7]],
                   [[5,6,7],
                   [6,7,9]]])
ten4.ndim

3

In [12]:
ten4.shape, tf.rank(ten4), tf.size(ten4)

(TensorShape([2, 2, 3]),
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=12>)

In [13]:
t5 = tf.random.uniform(shape=(5,300), minval=0, maxval=1, dtype=tf.float16)
t6 = tf.random.uniform(shape=(5,300), minval=0, maxval=1, dtype=tf.float16)
t5, t6

(<tf.Tensor: shape=(5, 300), dtype=float16, numpy=
 array([[0.331   , 0.0967  , 0.4658  , ..., 0.549   , 0.747   , 0.004883],
        [0.8613  , 0.2998  , 0.6094  , ..., 0.3242  , 0.3613  , 0.8477  ],
        [0.009766, 0.01758 , 0.083   , ..., 0.5967  , 0.1631  , 0.456   ],
        [0.503   , 0.6377  , 0.715   , ..., 0.912   , 0.42    , 0.1484  ],
        [0.5996  , 0.797   , 0.7373  , ..., 0.1279  , 0.925   , 0.824   ]],
       dtype=float16)>,
 <tf.Tensor: shape=(5, 300), dtype=float16, numpy=
 array([[0.7676 , 0.3086 , 0.505  , ..., 0.3477 , 0.7705 , 0.6875 ],
        [0.79   , 0.866  , 0.05566, ..., 0.783  , 0.3584 , 0.2217 ],
        [0.12305, 0.6865 , 0.992  , ..., 0.294  , 0.8115 , 0.2705 ],
        [0.577  , 0.9463 , 0.5    , ..., 0.552  , 0.415  , 0.4795 ],
        [0.10254, 0.03516, 0.4434 , ..., 0.1816 , 0.702  , 0.8076 ]],
       dtype=float16)>)

In [15]:
t5 * t6

<tf.Tensor: shape=(5, 300), dtype=float16, numpy=
array([[0.2542  , 0.02983 , 0.2352  , ..., 0.1908  , 0.5757  , 0.003357],
       [0.6807  , 0.2598  , 0.03394 , ..., 0.254   , 0.1295  , 0.1879  ],
       [0.001202, 0.01207 , 0.08234 , ..., 0.1754  , 0.1323  , 0.12335 ],
       [0.2903  , 0.6035  , 0.3574  , ..., 0.5034  , 0.1743  , 0.07117 ],
       [0.0615  , 0.02802 , 0.327   , ..., 0.02324 , 0.6494  , 0.6655  ]],
      dtype=float16)>

In [14]:
tf.matmul(t5, tf.transpose(t6))

<tf.Tensor: shape=(5, 5), dtype=float16, numpy=
array([[81.75, 76.  , 73.56, 77.9 , 70.4 ],
       [85.8 , 79.1 , 73.56, 79.25, 73.3 ],
       [78.2 , 70.75, 71.4 , 75.75, 70.06],
       [77.6 , 74.3 , 75.94, 76.75, 74.06],
       [83.3 , 78.8 , 78.3 , 81.75, 76.7 ]], dtype=float16)>

In [17]:
t6 = tf.random.uniform(shape=(224,224,3), minval=0, maxval=1, dtype=tf.float16)
t6

<tf.Tensor: shape=(224, 224, 3), dtype=float16, numpy=
array([[[0.07715, 0.759  , 0.3604 ],
        [0.9746 , 0.833  , 0.6104 ],
        [0.3604 , 0.7207 , 0.661  ],
        ...,
        [0.577  , 0.03125, 0.6875 ],
        [0.581  , 0.0664 , 0.255  ],
        [0.1406 , 0.2344 , 0.455  ]],

       [[0.334  , 0.6855 , 0.06055],
        [0.3643 , 0.421  , 0.3545 ],
        [0.01465, 0.508  , 0.21   ],
        ...,
        [0.0996 , 0.6406 , 0.827  ],
        [0.294  , 0.3936 , 0.99   ],
        [0.7627 , 0.4463 , 0.9473 ]],

       [[0.4746 , 0.9326 , 0.6416 ],
        [0.4385 , 0.2207 , 0.573  ],
        [0.3955 , 0.6973 , 0.1602 ],
        ...,
        [0.783  , 0.3164 , 0.8076 ],
        [0.02539, 0.9346 , 0.6494 ],
        [0.793  , 0.5693 , 0.4736 ]],

       ...,

       [[0.618  , 0.5225 , 0.3066 ],
        [0.2129 , 0.8057 , 0.3213 ],
        [0.7686 , 0.657  , 0.967  ],
        ...,
        [0.3506 , 0.2432 , 0.1123 ],
        [0.1484 , 0.5947 , 0.5273 ],
        [0.249  , 0.556

In [21]:
tf.reduce_max(t6, axis=1), tf.reduce_min(t6, axis=1)

(<tf.Tensor: shape=(224, 3), dtype=float16, numpy=
 array([[0.999 , 0.996 , 0.997 ],
        [0.996 , 0.998 , 0.995 ],
        [0.999 , 0.997 , 0.999 ],
        [0.9873, 0.996 , 0.9883],
        [0.995 , 0.993 , 0.998 ],
        [0.999 , 0.997 , 0.997 ],
        [0.999 , 0.995 , 0.997 ],
        [0.993 , 0.999 , 0.998 ],
        [0.997 , 0.999 , 0.996 ],
        [0.992 , 0.993 , 0.992 ],
        [0.998 , 0.999 , 0.998 ],
        [0.998 , 0.996 , 0.999 ],
        [0.996 , 0.998 , 0.999 ],
        [0.999 , 0.999 , 0.998 ],
        [0.995 , 0.995 , 0.991 ],
        [0.997 , 0.99  , 0.994 ],
        [0.995 , 0.9854, 0.9824],
        [0.991 , 0.998 , 0.99  ],
        [0.994 , 0.994 , 0.999 ],
        [0.999 , 0.995 , 0.999 ],
        [0.993 , 0.9893, 0.992 ],
        [0.998 , 0.994 , 0.999 ],
        [0.999 , 0.994 , 0.999 ],
        [0.994 , 0.991 , 0.99  ],
        [0.995 , 0.996 , 0.996 ],
        [0.998 , 0.999 , 0.998 ],
        [0.9863, 0.995 , 0.993 ],
        [0.9824, 0.99  , 0.998 

In [24]:
ten7 = tf.random.uniform(shape=[1,224,224,3])
tf.squeeze(ten7).shape

TensorShape([224, 224, 3])