In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Datatypes and attibutes

In [73]:
# Numpy main datatype is ndarray (N-dimensional Array)
a1 = np.array([1,2,3,4,5,6])

In [74]:
type(a1)

numpy.ndarray

In [99]:
a2 = np.array([[1,2,3],
              [6,7,8]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]],
              [[19,20,21],
              [22,23,24]]])

In [76]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [18]:
a3.shape, a3.ndim

((4, 2, 3), 3)

In [25]:
y = np.zeros((3, 3, 4))
y

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [24]:
y.ndim

3

In [28]:
a2.dtype

dtype('float64')

In [31]:
#Create a DataFrame from a numpy array -- DataFrame are built on top of ndarrays
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2    3     4
0  1.0  2.0  3.0  4.0   5.0
1  6.0  7.0  8.0  9.0  10.5

In [32]:
# Create Numpy arrays

sample_array = np.array([1,2,3])
sample_array



array([1, 2, 3])

In [33]:
sample_array.dtype

dtype('int32')

In [37]:
ones = np.ones((4,3))

In [46]:
ones.dtype

dtype('float64')

In [48]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [52]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[5, 5, 0, 8, 7],
       [7, 6, 0, 3, 6],
       [7, 2, 8, 0, 2]])

In [53]:
random_array.size, random_array.shape

(15, (3, 5))

In [55]:
random_array2 = np.random.random(size = (5,3))
random_array2

array([[0.30114607, 0.04328716, 0.0338421 ],
       [0.94499267, 0.70642687, 0.51776574],
       [0.45277328, 0.22808241, 0.77107664],
       [0.76644652, 0.47049138, 0.02433746],
       [0.53039339, 0.62372453, 0.34908428]])

In [60]:
random_array3 = np.random.rand(2,3,3)
random_array3

array([[[0.10398872, 0.31953978, 0.27618384],
        [0.81242649, 0.60990315, 0.25627328],
        [0.01751059, 0.13805964, 0.17822121]],

       [[0.03818595, 0.42447212, 0.25057755],
        [0.30466522, 0.64284491, 0.73023864],
        [0.98751239, 0.80269127, 0.65477858]]])

In [63]:
np.random.seed(3)

In [65]:
random_array4 = np.random.randint(4,5,size=(4,5))
random_array4

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

## Viewing Array and Metrics

In [67]:
np.unique(random_array)

array([0, 2, 3, 5, 6, 7, 8])

In [69]:
a3[2]

array([[13, 14, 15],
       [16, 17, 18]])

In [77]:
a1

array([1, 2, 3, 4, 5, 6])

In [78]:
a2

array([[ 1. ,  2. ,  3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ,  9. , 10.5]])

In [83]:
a1.reshape(2,3), a2.reshape(2,5)

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 1. ,  2. ,  3. ,  4. ,  5. ],
        [ 6. ,  7. ,  8. ,  9. , 10.5]]))

In [85]:
# floow division - removes the decimal from the matrix or arrays

a2//3.12

array([[0., 0., 0., 1., 1.],
       [1., 2., 2., 2., 3.]])

## Aggregation

In [86]:
list1 = [1,2,3,5]
list1

[1, 2, 3, 5]

In [87]:
sum(list1)

11

In [88]:
np.sum(list1)

11

 Use Python method ('Sum()') on Python Datatypes and use Numpy's methods on Numpy arrays (np.sum())

In [89]:
np.std(a1)

1.707825127659933

In [90]:
np.var(a2)

8.7225

In [92]:
massive_array = np.random.rand(100000)

In [93]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

7.23 ms ± 819 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
45.3 µs ± 2.74 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Reshape and Transpose

In [100]:
a2

array([[1, 2, 3],
       [6, 7, 8]])

In [101]:
a3.shape

(4, 2, 3)

In [103]:
a2.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[6],
        [7],
        [8]]])

In [104]:
a3.shape

(4, 2, 3)

In [133]:
np.random.seed(2)

mat1 = np.random.randint(5,10, size= (4,3))
mat2 = np.random.randint(4,67, size=(4,3))

In [134]:
 mat1*mat2  # THis is element wise multiplication (Hadamard product)

array([[280, 205, 344],
       [ 49, 336,  40],
       [322, 282, 440],
       [301, 378, 414]])

In [137]:
mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 829,  309,  905,  793],
       [ 935,  425,  973,  867],
       [ 982,  365, 1044,  921],
       [1148,  499, 1240, 1093]])

In [138]:
mat3.shape

(4, 4)

## Sorting Array

In [139]:
random_array4 = np.random.randint(19, size=(3,5))
random_array4

array([[ 1,  3,  5,  4, 14],
       [ 6,  2, 16, 14, 12],
       [18,  4, 15, 17,  7]])

In [140]:

random_array4.shape

(3, 5)

In [141]:
np.sort(random_array4)

array([[ 1,  3,  4,  5, 14],
       [ 2,  6, 12, 14, 16],
       [ 4,  7, 15, 17, 18]])

In [142]:
np.argsort(random_array4)

array([[0, 1, 3, 2, 4],
       [1, 0, 4, 3, 2],
       [1, 4, 2, 3, 0]], dtype=int64)

In [147]:
random_array4

array([[ 1,  3,  5,  4, 14],
       [ 6,  2, 16, 14, 12],
       [18,  4, 15, 17,  7]])

In [146]:
np.argmin(random_array4, axis=1)

array([0, 1, 1], dtype=int64)

<img src= "XML.PNG">